name: 'Terraform cdk Automation'

on:
  push:
    branches:
      - main   

jobs:
  terraform:
    #if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    name: 'Terraform-main'
    runs-on: ubuntu-latest
    
    #environment: dev  

    defaults:
      run:
        shell: bash
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2


      - name: Configure nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install cdkt
        run: npm install -g cdktf-cli

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Configure cdktf
        run: |
          mkdir cdk-init && cd cdk-init && cdktf init --template="python"

      - name: cdktf synth and diff or plan
        run: |
          cdktf synth
          cdktf diff