#test1
name: 'Terraform cdk Automation'

on:
  push:
    branches:
      - main   

jobs:
  terraform:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    name: 'Terraform-main'
    runs-on: ubuntu-latest
    
    env:
      TERRAFORM_CLOUD_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TYRELL_ENVIRONMENT: 'dev'
      TF_ACTION_WORKING_DIR: 'dev'

    defaults:
      run:
        shell: bash
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2


      - name: Configure nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install cdkt
        run: npm install -g cdktf-cli

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
          python -m pip install constructs cdktf cdktf-cdktf-provider-aws
         
          

      #- name: Configure cdktf
       # run: |
        #  cdktf init --template="python"
         #pipenv install
          #pipenv run cdktf synth
          #pipenv shell

      - name: cdktf synth and diff or plan
        run: |
          cd ec2
          cdktf synth
          cdktf diff
          cdktf deploy --auto-approve